### ISSUE TITLE
Str to float and QsciScintilla

### ISSUE THREAD

**Issue by selfus** [jjgomera/pychemqt#13]
On line 43 of costIndex.py there is an issue with converting str to float

` indiceActual.append(float(archivo.readline()))`

On line 44 codeEditor.py there is an issue with QsciScintilla, saying name is not defined

**Comment by jjgomera** [comment]
Two different problem:
costIndex: delete the .pychemqt/CostIndex.dat file and try again. Probably you have the old version file.
QSciScintilla: The QsciScintilla optional dependence is don't managed in code, so if you dont have it raise that error.
I think solved with last commit. Thanks!

**Comment by quantum0815** [comment]
I'm using today's version (on Win10, WinPython-32bit-3.5.3.0Qt5) and still get the error in 
\tools\costIndex.py, line 43, in <module>
    indiceActual.append(float(archivo.readline()))
ValueError: could not convert string to float: 

(even after deleting the CostIndex.dat file)

**Comment by jjgomera** [comment]
Try it with last commit. I think is solved.

Thanks for feedback!

**Comment by selfus** [comment]
All startup problems have been fixed for me.
Some more arrise when trying to use the software. Will keep reporting

**Comment by quantum0815** [comment]
yes, starting up ok now. Thanks for fixing. 
Will try to play a bit as I have time...
